/* AUTO-GENERATED by gen_coeffs — do not edit by hand */
#ifndef DSP_COEFFS_H
#define DSP_COEFFS_H

#define DSP_FS_HZ 48000
#define DSP_LPF_FC_HZ 100
#define DSP_HPF_FC_HZ 20

/* One Butterworth LPF section (Q=1/sqrt(2)); cascade twice for LR4 */
#define DSP_LPF_B0 (4.2443368140232844e-05)
#define DSP_LPF_B1 (8.4886736280465687e-05)
#define DSP_LPF_B2 (4.2443368140232844e-05)
#define DSP_LPF_A1 (-1.9814885091445731)
#define DSP_LPF_A2 (0.98165828261713406)

/* Butterworth HPF section @ 20 Hz (subsonic) */
#define DSP_HPF_B0 (0.99815051119045206)
#define DSP_HPF_B1 (-1.9963010223809041)
#define DSP_HPF_B2 (0.99815051119045206)
#define DSP_HPF_A1 (-1.9962976017691223)
#define DSP_HPF_A2 (0.99630444299268572)

#endif /* DSP_COEFFS_H */
