/*
 * Audio EQ Cookbook (Robert Bristow-Johnson) coefficient generator.
 * Writes ../dsp/dsp_coeffs.h for HPF 20 Hz and LPF Butterworth section (Q=1/sqrt(2))
 * used twice for Linkwitz-Riley 4th-order @ 100 Hz.
 */
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

struct Coeffs {
    double b0, b1, b2, a1, a2;
};

static Coeffs design_lpf(double fc, double Q, double fs)
{
    double w0 = 2.0 * M_PI * fc / fs;
    double cosw = std::cos(w0);
    double sinw = std::sin(w0);
    double alpha = sinw / (2.0 * Q);
    double a0 = 1.0 + alpha;
    Coeffs c;
    c.b0 = ((1.0 - cosw) / 2.0) / a0;
    c.b1 = (1.0 - cosw) / a0;
    c.b2 = ((1.0 - cosw) / 2.0) / a0;
    c.a1 = (-2.0 * cosw) / a0;
    c.a2 = (1.0 - alpha) / a0;
    return c;
}

static Coeffs design_hpf(double fc, double Q, double fs)
{
    double w0 = 2.0 * M_PI * fc / fs;
    double cosw = std::cos(w0);
    double sinw = std::sin(w0);
    double alpha = sinw / (2.0 * Q);
    double a0 = 1.0 + alpha;
    Coeffs c;
    c.b0 = ((1.0 + cosw) / 2.0) / a0;
    c.b1 = (-(1.0 + cosw)) / a0;
    c.b2 = ((1.0 + cosw) / 2.0) / a0;
    c.a1 = (-2.0 * cosw) / a0;
    c.a2 = (1.0 - alpha) / a0;
    return c;
}

int main(int argc, char **argv)
{
    const double fs = 48000.0;
    const double Q = 1.0 / std::sqrt(2.0); /* Butterworth / LR section */
    const char *out_path = "../dsp/dsp_coeffs.h";

    if (argc >= 2) {
        out_path = argv[1];
    }

    Coeffs lpf = design_lpf(100.0, Q, fs);
    Coeffs hpf = design_hpf(20.0, Q, fs);

    /* Reference check values from plan */
    const double ref_b0 = 4.2452e-05;
    const double ref_a1 = -1.981490;
    double err_b0 = std::fabs(lpf.b0 - ref_b0) / ref_b0;
    double err_a1 = std::fabs(lpf.a1 - ref_a1) / std::fabs(ref_a1);

    std::printf("LPF 100 Hz section:\n");
    std::printf("  b0=%.17g b1=%.17g b2=%.17g\n", lpf.b0, lpf.b1, lpf.b2);
    std::printf("  a1=%.17g a2=%.17g\n", lpf.a1, lpf.a2);
    std::printf("  vs plan: rel_err_b0=%.3e rel_err_a1=%.3e\n", err_b0, err_a1);
    std::printf("HPF 20 Hz:\n");
    std::printf("  b0=%.17g b1=%.17g b2=%.17g\n", hpf.b0, hpf.b1, hpf.b2);
    std::printf("  a1=%.17g a2=%.17g\n", hpf.a1, hpf.a2);

    if (err_b0 > 0.02 || err_a1 > 0.002) {
        std::fprintf(stderr, "ERROR: coefficients diverge from plan check values\n");
        return 1;
    }

    FILE *fp = std::fopen(out_path, "w");
    if (!fp) {
        std::perror(out_path);
        return 1;
    }

    std::fprintf(fp,
        "/* AUTO-GENERATED by gen_coeffs — do not edit by hand */\n"
        "#ifndef DSP_COEFFS_H\n"
        "#define DSP_COEFFS_H\n\n"
        "#define DSP_FS_HZ 48000\n"
        "#define DSP_LPF_FC_HZ 100\n"
        "#define DSP_HPF_FC_HZ 20\n\n"
        "/* One Butterworth LPF section (Q=1/sqrt(2)); cascade twice for LR4 */\n"
        "#define DSP_LPF_B0 (%.17g)\n"
        "#define DSP_LPF_B1 (%.17g)\n"
        "#define DSP_LPF_B2 (%.17g)\n"
        "#define DSP_LPF_A1 (%.17g)\n"
        "#define DSP_LPF_A2 (%.17g)\n\n"
        "/* Butterworth HPF section @ 20 Hz (subsonic) */\n"
        "#define DSP_HPF_B0 (%.17g)\n"
        "#define DSP_HPF_B1 (%.17g)\n"
        "#define DSP_HPF_B2 (%.17g)\n"
        "#define DSP_HPF_A1 (%.17g)\n"
        "#define DSP_HPF_A2 (%.17g)\n\n"
        "#endif /* DSP_COEFFS_H */\n",
        lpf.b0, lpf.b1, lpf.b2, lpf.a1, lpf.a2,
        hpf.b0, hpf.b1, hpf.b2, hpf.a1, hpf.a2);

    std::fclose(fp);
    std::printf("Wrote %s\n", out_path);
    return 0;
}
